# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7b46729a227fdb68dfd1bb17185c4de0154a3da1a74be045f30187b1ecd508b5a802aea721e7ebb13aa0cf7064eddef942310eb08e68675c0f76baae0753880

test:
  secret_key_base: 71777f83f3bc6bfcd83f3a76725c93899ee73df69e5a7be11daf6b74a53fcfdf671cd94fbfd60c4c7a6831afb4db9fc7319c1f4b063b49faadd287eb28cb5f6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
